name: Push

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
            sudo apt-get install -y make binutils build-essential diffutils gcc g++ patch gzip bzip2 perl tar cpio unzip rsync bc findutils cmake
            sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

      - name: Disable Swapfile
        run: |
            swapfile=$(sudo swapon --show=NAME --noheadings); echo "$swapfile"
            sudo swapoff "$swapfile"
            sudo rm -rf $swapfile

      - name: Remove apt cache
        run: |
            sudo apt clean

      - name: Clean up Docker
        run: |
            docker system prune -a -f
            sudo docker system prune -a -f

      - name: Get Disk
        run: |
            df -h
            free

      - name: Build
        run: |
            cd buildroot
            make BR2_EXTERNAL=$PWD/../ flipper_blackhat_a33_defconfig
            make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: push
          path: buildroot/output/images/sdcard.img
